package com.wucong.client.dto.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EvaluationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    public EvaluationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEvaluationIdIsNull() {
            addCriterion("wevaluation_id is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationIdIsNotNull() {
            addCriterion("wevaluation_id is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationIdEqualTo(String value) {
            addCriterion("wevaluation_id =", value, "evaluationId");
            return (Criteria) this;
        }

        public Criteria andEvaluationIdNotEqualTo(String value) {
            addCriterion("wevaluation_id <>", value, "evaluationId");
            return (Criteria) this;
        }

        public Criteria andEvaluationIdGreaterThan(String value) {
            addCriterion("wevaluation_id >", value, "evaluationId");
            return (Criteria) this;
        }

        public Criteria andEvaluationIdGreaterThanOrEqualTo(String value) {
            addCriterion("wevaluation_id >=", value, "evaluationId");
            return (Criteria) this;
        }

        public Criteria andEvaluationIdLessThan(String value) {
            addCriterion("wevaluation_id <", value, "evaluationId");
            return (Criteria) this;
        }

        public Criteria andEvaluationIdLessThanOrEqualTo(String value) {
            addCriterion("wevaluation_id <=", value, "evaluationId");
            return (Criteria) this;
        }

        public Criteria andEvaluationIdLike(String value) {
            addCriterion("wevaluation_id like", value, "evaluationId");
            return (Criteria) this;
        }

        public Criteria andEvaluationIdNotLike(String value) {
            addCriterion("wevaluation_id not like", value, "evaluationId");
            return (Criteria) this;
        }

        public Criteria andEvaluationIdIn(List<String> values) {
            addCriterion("wevaluation_id in", values, "evaluationId");
            return (Criteria) this;
        }

        public Criteria andEvaluationIdNotIn(List<String> values) {
            addCriterion("wevaluation_id not in", values, "evaluationId");
            return (Criteria) this;
        }

        public Criteria andEvaluationIdBetween(String value1, String value2) {
            addCriterion("wevaluation_id between", value1, value2, "evaluationId");
            return (Criteria) this;
        }

        public Criteria andEvaluationIdNotBetween(String value1, String value2) {
            addCriterion("wevaluation_id not between", value1, value2, "evaluationId");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderIdIsNull() {
            addCriterion("wevaluation_sender_id is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderIdIsNotNull() {
            addCriterion("wevaluation_sender_id is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderIdEqualTo(String value) {
            addCriterion("wevaluation_sender_id =", value, "evaluationSenderId");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderIdNotEqualTo(String value) {
            addCriterion("wevaluation_sender_id <>", value, "evaluationSenderId");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderIdGreaterThan(String value) {
            addCriterion("wevaluation_sender_id >", value, "evaluationSenderId");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderIdGreaterThanOrEqualTo(String value) {
            addCriterion("wevaluation_sender_id >=", value, "evaluationSenderId");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderIdLessThan(String value) {
            addCriterion("wevaluation_sender_id <", value, "evaluationSenderId");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderIdLessThanOrEqualTo(String value) {
            addCriterion("wevaluation_sender_id <=", value, "evaluationSenderId");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderIdLike(String value) {
            addCriterion("wevaluation_sender_id like", value, "evaluationSenderId");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderIdNotLike(String value) {
            addCriterion("wevaluation_sender_id not like", value, "evaluationSenderId");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderIdIn(List<String> values) {
            addCriterion("wevaluation_sender_id in", values, "evaluationSenderId");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderIdNotIn(List<String> values) {
            addCriterion("wevaluation_sender_id not in", values, "evaluationSenderId");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderIdBetween(String value1, String value2) {
            addCriterion("wevaluation_sender_id between", value1, value2, "evaluationSenderId");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderIdNotBetween(String value1, String value2) {
            addCriterion("wevaluation_sender_id not between", value1, value2, "evaluationSenderId");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderNameIsNull() {
            addCriterion("wevaluation_sender_name is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderNameIsNotNull() {
            addCriterion("wevaluation_sender_name is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderNameEqualTo(String value) {
            addCriterion("wevaluation_sender_name =", value, "evaluationSenderName");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderNameNotEqualTo(String value) {
            addCriterion("wevaluation_sender_name <>", value, "evaluationSenderName");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderNameGreaterThan(String value) {
            addCriterion("wevaluation_sender_name >", value, "evaluationSenderName");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderNameGreaterThanOrEqualTo(String value) {
            addCriterion("wevaluation_sender_name >=", value, "evaluationSenderName");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderNameLessThan(String value) {
            addCriterion("wevaluation_sender_name <", value, "evaluationSenderName");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderNameLessThanOrEqualTo(String value) {
            addCriterion("wevaluation_sender_name <=", value, "evaluationSenderName");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderNameLike(String value) {
            addCriterion("wevaluation_sender_name like", value, "evaluationSenderName");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderNameNotLike(String value) {
            addCriterion("wevaluation_sender_name not like", value, "evaluationSenderName");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderNameIn(List<String> values) {
            addCriterion("wevaluation_sender_name in", values, "evaluationSenderName");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderNameNotIn(List<String> values) {
            addCriterion("wevaluation_sender_name not in", values, "evaluationSenderName");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderNameBetween(String value1, String value2) {
            addCriterion("wevaluation_sender_name between", value1, value2, "evaluationSenderName");
            return (Criteria) this;
        }

        public Criteria andEvaluationSenderNameNotBetween(String value1, String value2) {
            addCriterion("wevaluation_sender_name not between", value1, value2, "evaluationSenderName");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverIdIsNull() {
            addCriterion("wevaluation_receiver_id is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverIdIsNotNull() {
            addCriterion("wevaluation_receiver_id is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverIdEqualTo(String value) {
            addCriterion("wevaluation_receiver_id =", value, "evaluationReceiverId");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverIdNotEqualTo(String value) {
            addCriterion("wevaluation_receiver_id <>", value, "evaluationReceiverId");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverIdGreaterThan(String value) {
            addCriterion("wevaluation_receiver_id >", value, "evaluationReceiverId");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverIdGreaterThanOrEqualTo(String value) {
            addCriterion("wevaluation_receiver_id >=", value, "evaluationReceiverId");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverIdLessThan(String value) {
            addCriterion("wevaluation_receiver_id <", value, "evaluationReceiverId");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverIdLessThanOrEqualTo(String value) {
            addCriterion("wevaluation_receiver_id <=", value, "evaluationReceiverId");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverIdLike(String value) {
            addCriterion("wevaluation_receiver_id like", value, "evaluationReceiverId");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverIdNotLike(String value) {
            addCriterion("wevaluation_receiver_id not like", value, "evaluationReceiverId");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverIdIn(List<String> values) {
            addCriterion("wevaluation_receiver_id in", values, "evaluationReceiverId");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverIdNotIn(List<String> values) {
            addCriterion("wevaluation_receiver_id not in", values, "evaluationReceiverId");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverIdBetween(String value1, String value2) {
            addCriterion("wevaluation_receiver_id between", value1, value2, "evaluationReceiverId");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverIdNotBetween(String value1, String value2) {
            addCriterion("wevaluation_receiver_id not between", value1, value2, "evaluationReceiverId");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverNameIsNull() {
            addCriterion("wevaluation_receiver_name is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverNameIsNotNull() {
            addCriterion("wevaluation_receiver_name is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverNameEqualTo(String value) {
            addCriterion("wevaluation_receiver_name =", value, "evaluationReceiverName");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverNameNotEqualTo(String value) {
            addCriterion("wevaluation_receiver_name <>", value, "evaluationReceiverName");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverNameGreaterThan(String value) {
            addCriterion("wevaluation_receiver_name >", value, "evaluationReceiverName");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverNameGreaterThanOrEqualTo(String value) {
            addCriterion("wevaluation_receiver_name >=", value, "evaluationReceiverName");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverNameLessThan(String value) {
            addCriterion("wevaluation_receiver_name <", value, "evaluationReceiverName");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverNameLessThanOrEqualTo(String value) {
            addCriterion("wevaluation_receiver_name <=", value, "evaluationReceiverName");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverNameLike(String value) {
            addCriterion("wevaluation_receiver_name like", value, "evaluationReceiverName");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverNameNotLike(String value) {
            addCriterion("wevaluation_receiver_name not like", value, "evaluationReceiverName");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverNameIn(List<String> values) {
            addCriterion("wevaluation_receiver_name in", values, "evaluationReceiverName");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverNameNotIn(List<String> values) {
            addCriterion("wevaluation_receiver_name not in", values, "evaluationReceiverName");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverNameBetween(String value1, String value2) {
            addCriterion("wevaluation_receiver_name between", value1, value2, "evaluationReceiverName");
            return (Criteria) this;
        }

        public Criteria andEvaluationReceiverNameNotBetween(String value1, String value2) {
            addCriterion("wevaluation_receiver_name not between", value1, value2, "evaluationReceiverName");
            return (Criteria) this;
        }

        public Criteria andEvaluationCommodityIdIsNull() {
            addCriterion("wevaluation_commodity_id is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationCommodityIdIsNotNull() {
            addCriterion("wevaluation_commodity_id is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationCommodityIdEqualTo(String value) {
            addCriterion("wevaluation_commodity_id =", value, "evaluationCommodityId");
            return (Criteria) this;
        }

        public Criteria andEvaluationCommodityIdNotEqualTo(String value) {
            addCriterion("wevaluation_commodity_id <>", value, "evaluationCommodityId");
            return (Criteria) this;
        }

        public Criteria andEvaluationCommodityIdGreaterThan(String value) {
            addCriterion("wevaluation_commodity_id >", value, "evaluationCommodityId");
            return (Criteria) this;
        }

        public Criteria andEvaluationCommodityIdGreaterThanOrEqualTo(String value) {
            addCriterion("wevaluation_commodity_id >=", value, "evaluationCommodityId");
            return (Criteria) this;
        }

        public Criteria andEvaluationCommodityIdLessThan(String value) {
            addCriterion("wevaluation_commodity_id <", value, "evaluationCommodityId");
            return (Criteria) this;
        }

        public Criteria andEvaluationCommodityIdLessThanOrEqualTo(String value) {
            addCriterion("wevaluation_commodity_id <=", value, "evaluationCommodityId");
            return (Criteria) this;
        }

        public Criteria andEvaluationCommodityIdLike(String value) {
            addCriterion("wevaluation_commodity_id like", value, "evaluationCommodityId");
            return (Criteria) this;
        }

        public Criteria andEvaluationCommodityIdNotLike(String value) {
            addCriterion("wevaluation_commodity_id not like", value, "evaluationCommodityId");
            return (Criteria) this;
        }

        public Criteria andEvaluationCommodityIdIn(List<String> values) {
            addCriterion("wevaluation_commodity_id in", values, "evaluationCommodityId");
            return (Criteria) this;
        }

        public Criteria andEvaluationCommodityIdNotIn(List<String> values) {
            addCriterion("wevaluation_commodity_id not in", values, "evaluationCommodityId");
            return (Criteria) this;
        }

        public Criteria andEvaluationCommodityIdBetween(String value1, String value2) {
            addCriterion("wevaluation_commodity_id between", value1, value2, "evaluationCommodityId");
            return (Criteria) this;
        }

        public Criteria andEvaluationCommodityIdNotBetween(String value1, String value2) {
            addCriterion("wevaluation_commodity_id not between", value1, value2, "evaluationCommodityId");
            return (Criteria) this;
        }

        public Criteria andEvaluationMessageIsNull() {
            addCriterion("wevaluation_message is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationMessageIsNotNull() {
            addCriterion("wevaluation_message is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationMessageEqualTo(String value) {
            addCriterion("wevaluation_message =", value, "evaluationMessage");
            return (Criteria) this;
        }

        public Criteria andEvaluationMessageNotEqualTo(String value) {
            addCriterion("wevaluation_message <>", value, "evaluationMessage");
            return (Criteria) this;
        }

        public Criteria andEvaluationMessageGreaterThan(String value) {
            addCriterion("wevaluation_message >", value, "evaluationMessage");
            return (Criteria) this;
        }

        public Criteria andEvaluationMessageGreaterThanOrEqualTo(String value) {
            addCriterion("wevaluation_message >=", value, "evaluationMessage");
            return (Criteria) this;
        }

        public Criteria andEvaluationMessageLessThan(String value) {
            addCriterion("wevaluation_message <", value, "evaluationMessage");
            return (Criteria) this;
        }

        public Criteria andEvaluationMessageLessThanOrEqualTo(String value) {
            addCriterion("wevaluation_message <=", value, "evaluationMessage");
            return (Criteria) this;
        }

        public Criteria andEvaluationMessageLike(String value) {
            addCriterion("wevaluation_message like", value, "evaluationMessage");
            return (Criteria) this;
        }

        public Criteria andEvaluationMessageNotLike(String value) {
            addCriterion("wevaluation_message not like", value, "evaluationMessage");
            return (Criteria) this;
        }

        public Criteria andEvaluationMessageIn(List<String> values) {
            addCriterion("wevaluation_message in", values, "evaluationMessage");
            return (Criteria) this;
        }

        public Criteria andEvaluationMessageNotIn(List<String> values) {
            addCriterion("wevaluation_message not in", values, "evaluationMessage");
            return (Criteria) this;
        }

        public Criteria andEvaluationMessageBetween(String value1, String value2) {
            addCriterion("wevaluation_message between", value1, value2, "evaluationMessage");
            return (Criteria) this;
        }

        public Criteria andEvaluationMessageNotBetween(String value1, String value2) {
            addCriterion("wevaluation_message not between", value1, value2, "evaluationMessage");
            return (Criteria) this;
        }

        public Criteria andEvaluationNumIsNull() {
            addCriterion("wevaluation_num is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationNumIsNotNull() {
            addCriterion("wevaluation_num is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationNumEqualTo(Integer value) {
            addCriterion("wevaluation_num =", value, "evaluationNum");
            return (Criteria) this;
        }

        public Criteria andEvaluationNumNotEqualTo(Integer value) {
            addCriterion("wevaluation_num <>", value, "evaluationNum");
            return (Criteria) this;
        }

        public Criteria andEvaluationNumGreaterThan(Integer value) {
            addCriterion("wevaluation_num >", value, "evaluationNum");
            return (Criteria) this;
        }

        public Criteria andEvaluationNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("wevaluation_num >=", value, "evaluationNum");
            return (Criteria) this;
        }

        public Criteria andEvaluationNumLessThan(Integer value) {
            addCriterion("wevaluation_num <", value, "evaluationNum");
            return (Criteria) this;
        }

        public Criteria andEvaluationNumLessThanOrEqualTo(Integer value) {
            addCriterion("wevaluation_num <=", value, "evaluationNum");
            return (Criteria) this;
        }

        public Criteria andEvaluationNumIn(List<Integer> values) {
            addCriterion("wevaluation_num in", values, "evaluationNum");
            return (Criteria) this;
        }

        public Criteria andEvaluationNumNotIn(List<Integer> values) {
            addCriterion("wevaluation_num not in", values, "evaluationNum");
            return (Criteria) this;
        }

        public Criteria andEvaluationNumBetween(Integer value1, Integer value2) {
            addCriterion("wevaluation_num between", value1, value2, "evaluationNum");
            return (Criteria) this;
        }

        public Criteria andEvaluationNumNotBetween(Integer value1, Integer value2) {
            addCriterion("wevaluation_num not between", value1, value2, "evaluationNum");
            return (Criteria) this;
        }

        public Criteria andEvaluationLevelIsNull() {
            addCriterion("wevaluation_level is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationLevelIsNotNull() {
            addCriterion("wevaluation_level is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationLevelEqualTo(BigDecimal value) {
            addCriterion("wevaluation_level =", value, "evaluationLevel");
            return (Criteria) this;
        }

        public Criteria andEvaluationLevelNotEqualTo(BigDecimal value) {
            addCriterion("wevaluation_level <>", value, "evaluationLevel");
            return (Criteria) this;
        }

        public Criteria andEvaluationLevelGreaterThan(BigDecimal value) {
            addCriterion("wevaluation_level >", value, "evaluationLevel");
            return (Criteria) this;
        }

        public Criteria andEvaluationLevelGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("wevaluation_level >=", value, "evaluationLevel");
            return (Criteria) this;
        }

        public Criteria andEvaluationLevelLessThan(BigDecimal value) {
            addCriterion("wevaluation_level <", value, "evaluationLevel");
            return (Criteria) this;
        }

        public Criteria andEvaluationLevelLessThanOrEqualTo(BigDecimal value) {
            addCriterion("wevaluation_level <=", value, "evaluationLevel");
            return (Criteria) this;
        }

        public Criteria andEvaluationLevelIn(List<BigDecimal> values) {
            addCriterion("wevaluation_level in", values, "evaluationLevel");
            return (Criteria) this;
        }

        public Criteria andEvaluationLevelNotIn(List<BigDecimal> values) {
            addCriterion("wevaluation_level not in", values, "evaluationLevel");
            return (Criteria) this;
        }

        public Criteria andEvaluationLevelBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wevaluation_level between", value1, value2, "evaluationLevel");
            return (Criteria) this;
        }

        public Criteria andEvaluationLevelNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wevaluation_level not between", value1, value2, "evaluationLevel");
            return (Criteria) this;
        }

        public Criteria andEvaluationImageIsNull() {
            addCriterion("wevaluation_image is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationImageIsNotNull() {
            addCriterion("wevaluation_image is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationImageEqualTo(String value) {
            addCriterion("wevaluation_image =", value, "evaluationImage");
            return (Criteria) this;
        }

        public Criteria andEvaluationImageNotEqualTo(String value) {
            addCriterion("wevaluation_image <>", value, "evaluationImage");
            return (Criteria) this;
        }

        public Criteria andEvaluationImageGreaterThan(String value) {
            addCriterion("wevaluation_image >", value, "evaluationImage");
            return (Criteria) this;
        }

        public Criteria andEvaluationImageGreaterThanOrEqualTo(String value) {
            addCriterion("wevaluation_image >=", value, "evaluationImage");
            return (Criteria) this;
        }

        public Criteria andEvaluationImageLessThan(String value) {
            addCriterion("wevaluation_image <", value, "evaluationImage");
            return (Criteria) this;
        }

        public Criteria andEvaluationImageLessThanOrEqualTo(String value) {
            addCriterion("wevaluation_image <=", value, "evaluationImage");
            return (Criteria) this;
        }

        public Criteria andEvaluationImageLike(String value) {
            addCriterion("wevaluation_image like", value, "evaluationImage");
            return (Criteria) this;
        }

        public Criteria andEvaluationImageNotLike(String value) {
            addCriterion("wevaluation_image not like", value, "evaluationImage");
            return (Criteria) this;
        }

        public Criteria andEvaluationImageIn(List<String> values) {
            addCriterion("wevaluation_image in", values, "evaluationImage");
            return (Criteria) this;
        }

        public Criteria andEvaluationImageNotIn(List<String> values) {
            addCriterion("wevaluation_image not in", values, "evaluationImage");
            return (Criteria) this;
        }

        public Criteria andEvaluationImageBetween(String value1, String value2) {
            addCriterion("wevaluation_image between", value1, value2, "evaluationImage");
            return (Criteria) this;
        }

        public Criteria andEvaluationImageNotBetween(String value1, String value2) {
            addCriterion("wevaluation_image not between", value1, value2, "evaluationImage");
            return (Criteria) this;
        }

        public Criteria andEvaluationVideoIsNull() {
            addCriterion("wevaluation_video is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationVideoIsNotNull() {
            addCriterion("wevaluation_video is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationVideoEqualTo(String value) {
            addCriterion("wevaluation_video =", value, "evaluationVideo");
            return (Criteria) this;
        }

        public Criteria andEvaluationVideoNotEqualTo(String value) {
            addCriterion("wevaluation_video <>", value, "evaluationVideo");
            return (Criteria) this;
        }

        public Criteria andEvaluationVideoGreaterThan(String value) {
            addCriterion("wevaluation_video >", value, "evaluationVideo");
            return (Criteria) this;
        }

        public Criteria andEvaluationVideoGreaterThanOrEqualTo(String value) {
            addCriterion("wevaluation_video >=", value, "evaluationVideo");
            return (Criteria) this;
        }

        public Criteria andEvaluationVideoLessThan(String value) {
            addCriterion("wevaluation_video <", value, "evaluationVideo");
            return (Criteria) this;
        }

        public Criteria andEvaluationVideoLessThanOrEqualTo(String value) {
            addCriterion("wevaluation_video <=", value, "evaluationVideo");
            return (Criteria) this;
        }

        public Criteria andEvaluationVideoLike(String value) {
            addCriterion("wevaluation_video like", value, "evaluationVideo");
            return (Criteria) this;
        }

        public Criteria andEvaluationVideoNotLike(String value) {
            addCriterion("wevaluation_video not like", value, "evaluationVideo");
            return (Criteria) this;
        }

        public Criteria andEvaluationVideoIn(List<String> values) {
            addCriterion("wevaluation_video in", values, "evaluationVideo");
            return (Criteria) this;
        }

        public Criteria andEvaluationVideoNotIn(List<String> values) {
            addCriterion("wevaluation_video not in", values, "evaluationVideo");
            return (Criteria) this;
        }

        public Criteria andEvaluationVideoBetween(String value1, String value2) {
            addCriterion("wevaluation_video between", value1, value2, "evaluationVideo");
            return (Criteria) this;
        }

        public Criteria andEvaluationVideoNotBetween(String value1, String value2) {
            addCriterion("wevaluation_video not between", value1, value2, "evaluationVideo");
            return (Criteria) this;
        }

        public Criteria andEvaluationCreateTimeIsNull() {
            addCriterion("wevaluation_create_time is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationCreateTimeIsNotNull() {
            addCriterion("wevaluation_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationCreateTimeEqualTo(Date value) {
            addCriterion("wevaluation_create_time =", value, "evaluationCreateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluationCreateTimeNotEqualTo(Date value) {
            addCriterion("wevaluation_create_time <>", value, "evaluationCreateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluationCreateTimeGreaterThan(Date value) {
            addCriterion("wevaluation_create_time >", value, "evaluationCreateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluationCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("wevaluation_create_time >=", value, "evaluationCreateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluationCreateTimeLessThan(Date value) {
            addCriterion("wevaluation_create_time <", value, "evaluationCreateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluationCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("wevaluation_create_time <=", value, "evaluationCreateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluationCreateTimeIn(List<Date> values) {
            addCriterion("wevaluation_create_time in", values, "evaluationCreateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluationCreateTimeNotIn(List<Date> values) {
            addCriterion("wevaluation_create_time not in", values, "evaluationCreateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluationCreateTimeBetween(Date value1, Date value2) {
            addCriterion("wevaluation_create_time between", value1, value2, "evaluationCreateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluationCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("wevaluation_create_time not between", value1, value2, "evaluationCreateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluationSignIsNull() {
            addCriterion("wevaluation_sign is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationSignIsNotNull() {
            addCriterion("wevaluation_sign is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationSignEqualTo(String value) {
            addCriterion("wevaluation_sign =", value, "evaluationSign");
            return (Criteria) this;
        }

        public Criteria andEvaluationSignNotEqualTo(String value) {
            addCriterion("wevaluation_sign <>", value, "evaluationSign");
            return (Criteria) this;
        }

        public Criteria andEvaluationSignGreaterThan(String value) {
            addCriterion("wevaluation_sign >", value, "evaluationSign");
            return (Criteria) this;
        }

        public Criteria andEvaluationSignGreaterThanOrEqualTo(String value) {
            addCriterion("wevaluation_sign >=", value, "evaluationSign");
            return (Criteria) this;
        }

        public Criteria andEvaluationSignLessThan(String value) {
            addCriterion("wevaluation_sign <", value, "evaluationSign");
            return (Criteria) this;
        }

        public Criteria andEvaluationSignLessThanOrEqualTo(String value) {
            addCriterion("wevaluation_sign <=", value, "evaluationSign");
            return (Criteria) this;
        }

        public Criteria andEvaluationSignLike(String value) {
            addCriterion("wevaluation_sign like", value, "evaluationSign");
            return (Criteria) this;
        }

        public Criteria andEvaluationSignNotLike(String value) {
            addCriterion("wevaluation_sign not like", value, "evaluationSign");
            return (Criteria) this;
        }

        public Criteria andEvaluationSignIn(List<String> values) {
            addCriterion("wevaluation_sign in", values, "evaluationSign");
            return (Criteria) this;
        }

        public Criteria andEvaluationSignNotIn(List<String> values) {
            addCriterion("wevaluation_sign not in", values, "evaluationSign");
            return (Criteria) this;
        }

        public Criteria andEvaluationSignBetween(String value1, String value2) {
            addCriterion("wevaluation_sign between", value1, value2, "evaluationSign");
            return (Criteria) this;
        }

        public Criteria andEvaluationSignNotBetween(String value1, String value2) {
            addCriterion("wevaluation_sign not between", value1, value2, "evaluationSign");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_evaluation
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}