package com.wucong.client.dto.mapper;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;
import com.wucong.client.dto.model.Evaluation;
import com.wucong.client.dto.model.EvaluationExample;

import java.util.List;

@Repository
public interface EvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    long countByExample(EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    int deleteByExample(EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String evaluationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    int insert(Evaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    int insertSelective(Evaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    List<Evaluation> selectByExampleWithRowbounds(EvaluationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    List<Evaluation> selectByExample(EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    Evaluation selectByPrimaryKey(String evaluationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Evaluation record, @Param("example") EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Evaluation record, @Param("example") EvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Evaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_evaluation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Evaluation record);
}